packages:
  - packages/*
  - apps/*

allowBuilds:
  es5-ext: false
  esbuild: true
  msgpackr-extract: true
  sharp: false
  vue-demi: false
  workerd: true

minimumReleaseAgeExclude:
  - "@effect/ai-openai-compat@4.0.0-beta.97"
  - "@effect/platform-node-shared@4.0.0-beta.97"
  - "@effect/platform-node@4.0.0-beta.97"
  - "@effect/vitest@4.0.0-beta.97"
  - "@types/node@26.1.1"
  - effect@4.0.0-beta.97
  - effect-workerd@0.0.11
  - liminal-util@0.0.15
  - liminal@0.17.21
  - "@effect/platform-node@4.0.0-beta.97"
  - "@opentui/core@0.1.97"
  - "@opentui/solid@0.1.97"

patchedDependencies:
  "@effect/ai-openai-compat@4.0.0-beta.97": patches/@effect__ai-openai-compat@4.0.0-beta.97.patch

packageExtensions:
  liminal:
    exports:
      ".":
        types: ./dist/index.d.ts
        workerd: ./dist/index.js
        browser: ./dist/index.non-workerd.js
        node: ./dist/index.non-workerd.js
        default: ./dist/index.js
      "./*":
        types: ./dist/*.d.ts
        default: ./dist/*.js
      "./experimental":
        types: ./dist/experimental/index.d.ts
        default: ./dist/experimental/index.js
      "./package.json": ./package.json
  effect-workerd:
    exports:
      ".":
        types: ./dist/index.d.ts
        default: ./dist/index.js
      "./*":
        types: ./dist/*.d.ts
        default: ./dist/*.js
      "./platform":
        types: ./dist/platform/index.d.ts
        default: ./dist/platform/index.js
      "./observability":
        types: ./dist/observability/index.d.ts
        default: ./dist/observability/index.js
  liminal-util:
    exports:
      "./*":
        types: ./dist/*.d.ts
        default: ./dist/*.js
      "./alchemicals/*":
        types: ./dist/alchemicals/*.d.ts
        default: ./dist/alchemicals/*.js
